# Generated by Django 3.2.19 on 2023-12-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='user_image')),
                ('students', models.ManyToManyField(blank=True, related_name='teachers', to='student.Student')),
            ],
        ),
    ]
