# Generated by Django 3.2.19 on 2024-02-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='user_image')),
                ('date_of_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_and_time_of_task_assigned', models.CharField(blank=True, max_length=200, null=True)),
                ('students', models.ManyToManyField(blank=True, related_name='teachers', to='student.Student')),
            ],
        ),
    ]
