# Generated by Django 3.2.19 on 2024-02-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='childrens',
            field=models.ManyToManyField(blank=True, related_name='parents', to='student.Student'),
        ),
    ]
