# Generated by Django 3.2.19 on 2023-12-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_user_is_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
