# Generated by Django 3.2.19 on 2024-01-04 06:53

import django.core.validators
from django.db import migrations
import user_account.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_auto_20231229_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=user_account.models.mobile_num_validator(blank=True, max_length=50, null=True, unique=True, validators=[user_account.models.no_repeating_digits_validator, django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(6)]),
        ),
    ]
