# Generated by Django 3.2.19 on 2023-12-15 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_teacher',
            field=models.ManyToManyField(related_name='assigned_tasks', to='teacher.Teacher'),
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task_type'),
        ),
    ]
