# Generated by Django 3.2.19 on 2023-12-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_of_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
