# Generated by Django 3.2.19 on 2023-12-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20231220_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='upload_media_hint',
            field=models.FileField(blank=True, null=True, upload_to='user_iamge'),
        ),
    ]
