# Generated by Django 3.2.19 on 2023-12-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_upload_media_hint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='upload_media_hint',
        ),
    ]
