# Generated by Django 3.2.19 on 2024-01-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_remove_task_upload_media_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_image_for_hint',
            field=models.FileField(blank=True, null=True, upload_to='user_image'),
        ),
    ]
