# Generated by Django 3.2.19 on 2024-01-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_task_task_image_for_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tutor_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
