# Generated by Django 3.2.19 on 2024-02-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_assignment_teacher'),
        ('student', '0003_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='task_assign',
            field=models.ManyToManyField(blank=True, to='task_app.Task'),
        ),
    ]
