# Generated by Django 3.2.19 on 2024-02-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_of_posted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
