# Generated by Django 3.2.19 on 2024-02-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_assignment_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='completion_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
