# Generated by Django 3.2.19 on 2024-02-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_alter_task_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_image_for_hint',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tutor_remark',
        ),
    ]
