# Generated by Django 3.2.19 on 2024-02-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_auto_20240208_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_type',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_image'),
        ),
    ]
